// frontend/src/pages/NotFoundPage.vue
<template>
  <div
    class="d-flex flex-column justify-content-center align-items-center vh-100 text-center"
  >
    <h1 class="display-3 text-danger mb-3">404</h1>
    <h4 class="mb-3">Page Not Found</h4>
    <p class="text-muted mb-4">
      The page you're looking for doesn't exist or has been moved.
    </p>
    <!-- <router-link to="/" class="btn btn-primary"> Go Back Home </router-link> -->
  </div>
</template>

<script>
export default {
  name: "NotFoundPage",
};
</script>

// frontend/src/pages/NotFoundPage.tsx
import { Button, Container, Typography } from "@mui/material";
import { useNavigate } from "react-router-dom";

export default function NotFoundPage() {
  const navigate = useNavigate();

  return (
    <Container
      maxWidth="lg"
      className="flex flex-col items-center justify-center h-screen text-center"
    >
      <Typography
        variant="h1"
        className="text-7xl font-bold text-blue-600 mb-4"
      >
        404
      </Typography>
      <Typography variant="h5" className="text-gray-700 mb-6">
        Oops! The page you are looking for does not exist.
      </Typography>
      <Button
        variant="contained"
        color="primary"
        onClick={() => navigate("/")}
        className="px-6 py-2 rounded-lg"
      >
        Go Back Home
      </Button>
    </Container>
  );
}
