// frontend/src/pages/LoginPage.tsx
import React, { useState } from "react";
import {
  Box,
  Button,
  Container,
  TextField,
  Typography,
  Paper,
} from "@mui/material";
import { http } from "../services/http";
import { toast, ToastContainer } from "react-toastify";
import { useNavigate } from "react-router-dom";

const LoginPage = () => {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    console.log({ username, password });
    await http
      .post("auth/login", { username, password })
      .then((res) => {
        console.log(res.data);
        if (res.data.status === "success") {
          navigate("/");
        }
      })
      .catch(() => {
        toast.error(`Error`, {
          position: "top-right",
        });
      });
  };

  return (
    <Container
      maxWidth="xs"
      sx={{
        minHeight: "100vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
      }}
    >
      <ToastContainer />
      <Paper elevation={3} sx={{ p: 4, width: "100%" }}>
        <Typography variant="h5" align="center" gutterBottom>
          Login
        </Typography>
        <Box component="form" onSubmit={handleSubmit} noValidate>
          <TextField
            margin="normal"
            fullWidth
            required
            id="username"
            name="username"
            label="Username"
            autoFocus
            value={username}
            onChange={(e) => {
              setUsername(e.target.value);
            }}
          />
          <TextField
            margin="normal"
            fullWidth
            required
            id="password"
            name="password"
            label="Password"
            type="password"
            value={password}
            onChange={(e) => {
              setPassword(e.target.value);
            }}
          />
          <Button
            type="submit"
            fullWidth
            variant="contained"
            sx={{ mt: 2, py: 1.2 }}
          >
            Sign In
          </Button>
        </Box>
      </Paper>
    </Container>
  );
};

export default LoginPage;

// frontend/src/pages/admin/LoginPage.vue
<template>
  <div class="d-flex justify-content-center align-items-center min-vh-100">
    <div class="card p-4 mx-auto" style="max-width: 400px">
      <h3 class="text-center mb-4">{{ $t("loginPage.title") }}</h3>
      <form @submit.prevent="handleSubmit">
        <div class="mb-3">
          <label class="form-label">{{ $t("loginPage.username") }}</label>
          <input type="text" class="form-control" v-model="username" required />
        </div>
        <div class="mb-3">
          <label class="form-label">{{ $t("loginPage.password") }}</label>
          <input
            type="password"
            class="form-control"
            v-model="password"
            required
          />
        </div>
        <div class="mb-3">
          <label class="form-label">{{ $t("loginPage.language") }}</label>
          <select class="form-select" v-model="lang" @change="changeLanguage">
            <option value="en">English</option>
            <option value="ar">العربية</option>
          </select>
        </div>
        <button type="submit" class="btn btn-primary w-100">
          {{ $t("loginPage.title") }}
        </button>
      </form>
    </div>
  </div>
</template>

<script>
import { useAuthStore } from "../../stores/auth";

export default {
  data() {
    return {
      username: "",
      password: "",
      lang: "en",
      user: {},
    };
  },
  methods: {
    async handleSubmit() {
      await this.$http
        .post("auth/login", {
          username: this.username,
          password: this.password,
        })
        .then((res) => {
          console.log(res);
          if (res.status === "success") {
            const authStore = useAuthStore();
            authStore.login(res.data.user, res.data.auth_token);
            this.$router.push({ name: "AdminDashboard" });
          }
        })
        .catch((err) => {
          console.log(err);
          if (err.status === 401) {
            this.$toast.error(
              this.$i18n.locale === "ar"
                ? err.response.data.data.message_ar
                : err.response.data.data.message_en
            );
          } else {
            console.log(err.response.data.data.message[0].message);

            this.$toast.error(err.response.data.data.message[0].message);
          }
        });
    },

    changeLanguage() {
      this.$i18n.locale = this.lang;

      if (this.lang === "ar") {
        document.documentElement.dir = "rtl";
        document.body.style.fontFamily = "'Cairo', sans-serif";
      } else {
        document.documentElement.dir = "ltr";
        document.body.style.fontFamily = "'Roboto', sans-serif";
      }
    },
  },
  mounted() {},
};
</script>
